### ISSUE TITLE
I got an error in ruby projects

### ISSUE THREAD

**Issue by brunoadacosta** [calebsmith/vim-lambdify#14]
Error detected while processing function vimlambdify#lambdify:
line    3:
E168: :finish used outside of a sourced file
E168: :finish used outside of a sourced file
Error detected while processing function vimlambdify#lambdify_match:
line    3:
E168: :finish used outside of a sourced file

my .vimrc

set nocompatible              " be iMproved, required
filetype off " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()
Plugin 'gmarik/Vundle.vim'

" Bundles
Plugin 'tpope/vim-surround'
Plugin 'ervandew/supertab'
Plugin 'Lokaltog/vim-powerline'
"Plugin 'bling/vim-airline'
Plugin 'vim-ruby/vim-ruby'
Plugin 'tpope/vim-rails'
Plugin 'Keithbsmiley/rspec.vim'
Plugin 'tpope/vim-endwise'
Plugin 'edsono/vim-matchit'
Plugin 'kien/ctrlp.vim'
Plugin 'Raimondi/delimitMate'
Plugin 'tpope/vim-commentary'
Plugin 'mattn/webapi-vim'
Plugin 'mattn/gist-vim'
Plugin 'danro/rename.vim'
Plugin 'thoughtbot/vim-rspec'
Plugin 'aaronj1335/underscore-templates.vim'
Plugin 'MarcWeber/vim-addon-mw-utils'
Plugin 'tomtom/tlib_vim'
Plugin 'bridgeutopia/snipmate-snippets'
Plugin 'garbas/vim-snipmate'
Plugin 'vim-scripts/bufkill.vim'
Plugin 'Lokaltog/vim-easymotion'
Plugin 'scrooloose/nerdtree'
Plugin 'pangloss/vim-javascript'
Plugin 'jeyb/vim-jst'
Plugin 'terryma/vim-multiple-cursors' 
"Plugin 'scrooloose/syntastic'
Plugin 'gorkunov/smartpairs.vim'
Plugin 'pbrisbin/vim-mkdir'
Plugin 'fatih/vim-go'
Plugin 'mattonrails/vim-mix'
Plugin 'elixir-lang/vim-elixir'
Plugin 'carlosgaldino/elixir-snippets'
Plugin 'rking/ag.vim'
"Plugin 'rainerborene/vim-reek'
Plugin 'raichoo/haskell-vim'
Plugin 'dsawardekar/ember.vim'
Plugin 'mustache/vim-mustache-handlebars'
Plugin 'vim-scripts/c.vim'
Plugin 'airblade/vim-gitgutter'
Plugin 'calebsmith/vim-lambdify'

call vundle#end()  

filetype plugin indent on
syntax on

set history=100
set nobackup
set noswapfile
set pastetoggle=<F6>
set mouse=a
set encoding=utf-8

set title
set titleold=
set ruler
set number

set backspace=2        " indent,eol,start
set whichwrap+=<,>,h,l
set shortmess=aTsI     " see :help shortmess
set noerrorbells
set visualbell
set scrolloff=3
set sidescroll=3

set autoread
set splitright
set splitbelow
set hidden
set clipboard=unnamed

set timeoutlen=500
set showmatch
set matchtime=1
set hlsearch
set incsearch
set ignorecase
" set list
" set listchars=eol:$,trail:·,tab:>·
set laststatus=2

set autoindent
set smartindent
set expandtab
set tabstop=2
set softtabstop=2
set shiftwidth=2
set nowrap
set textwidth=80
set linebreak

set foldenable
set foldmethod=expr
set foldexpr=getline(v:lnum)=~'^\\s\\+#'  " fold comments
set foldminlines=4
set foldopen-=undo      " don't open folds when you undo stuff

set virtualedit=block

autocmd BufRead *irb-interactive* setl ft=ruby
autocmd BufRead nginx.conf setl ft=nginx
autocmd BufRead *.jst.ejs setl ft=jst

" Reek
let g:reek_always_show = 0

" Syntastic
" let g:syntastic_ruby_checkers = ['rubocop']
" let g:syntastic_javascript_checkers = ['jslint']

" Mappings
nnoremap <silent> <C-L> :nohls<cr>
nmap Q <nop>
nmap K <nop>
nmap U <nop>

" Remove trailing spaces
autocmd FileType ruby,eruby,javascript,jst,go autocmd BufWritePre <buffer> :%s/\s\+$//e

" Multiple cursors
let g:multi_cursor_use_default_mapping=0
let g:multi_cursor_start_key='<F5>'
let g:multi_cursor_next_key='<C-n>'
let g:multi_cursor_prev_key='<C-p>'
let g:multi_cursor_skip_key='<C-k>'
let g:multi_cursor_quit_key='<Esc>'

" Powerline
let g:Powerline_symbols='fancy'

" ctrlp
set wildignore+=*/tmp/*
set wildignore+=vendor/bundle,vendor/ruby
set wildignore+=*.png,*.jpg,*.gif,*.gem,*.o,*.so,*.swp,*.zip,*.log
let g:ctrlp_custom_ignore = '\v[\/]\.(git|hg|svn)$'

" ctrlpBuffer
" nnoremap <silent> ,b <CR>:CtrlPBuffer<cr>
nnoremap <silent> <C-b> <CR>:CtrlPBuffer<cr>
" let g:ctrlp_show_hidden = 1

" gist
let g:gist_clip_command = 'pbcopy'

" rspec
au FileType ruby map <Leader>r :call RunCurrentSpecFile()<CR>
au FileType ruby map <Leader>s :call RunNearestSpec()<CR>
au FileType ruby map <Leader>a :call RunAllSpecs()<CR>
au FileType ruby let g:rspec_command = "!bundle exec rspec --drb {spec}"

" go
au FileType go nmap <Leader>s <Plug>(go-implements)
au FileType go nmap <Leader>i <Plug>(go-info)
au FileType go nmap <Leader>gd <Plug>(go-doc)
au FileType go nmap <Leader>gv <Plug>(go-doc-vertical)
au FileType go nmap <leader>r <Plug>(go-run)
au FileType go nmap <leader>b <Plug>(go-build)
au FileType go nmap <leader>t <Plug>(go-test)
au FileType go nmap <leader>c <Plug>(go-coverage)
au FileType go nmap <Leader>ds <Plug>(go-def-split)
au FileType go nmap <Leader>dv <Plug>(go-def-vertical)
au FileType go nmap <Leader>dt <Plug>(go-def-tab)

" easymotion
map <Leader> <Plug>(easymotion-prefix)

" NerdTree
nnoremap <silent> <C-n> :NERDTreeToggle<CR>

**Comment by calebsmith** [comment]
Thanks for reporting this bug!

I don't know off-hand what is going on but I have a suspicion of where to look.

I think the failure is happening here:
https://github.com/calebsmith/vim-lambdify/blob/master/autoload/vimlambdify.vim#L4

It may have been incorrect to use :finish here based on the error. I think there must be a more appropriate way for the script to bail if the conceal feature is missing, which is the intention of that code.

I *think* that you are encountering this because your vim doesn't support the conceal feature. At one time, I thought this required vim 7.3 but I think 7.4 is required. Therefore, as a short-term solution, I would try upgrading vim to >= 7.4 if it isn't. Feel free to report back if that helps or doesn't

**Comment by brunoadacosta** [comment]
Thanks for de feedback.

my vim is 7.4

```
$ vim --version
VIM - Vi IMproved 7.4 (2013 Aug 10, compiled Feb  2 2016 10:58:53)
MacOS X (unix) version
Included patches: 1-1202
```

**Comment by brunoadacosta** [comment]
omg! sorry, in one my terminal tab's my vim is 9.3 


Sorry :(
