### ISSUE TITLE
Conflict with indentLine

### ISSUE THREAD

**Issue by adelarsq** [calebsmith/vim-lambdify#6]
[IndentLine](https://github.com/Yggdroot/indentLine) and vim-lambdify are using the same hightlight:

![t](https://cloud.githubusercontent.com/assets/430272/6765310/e5028196-cfb8-11e4-9a60-72f42f1dbd69.png)

It's possible to use different colors?

**Comment by calebsmith** [comment]
Interesting. I haven't looked very deeply into coloration yet. I suspect that the syn match that matches the lambda could be keyed off of for color. In most languages, the color seems appropriate enough that I just haven't tried changing it. I can see how in the above its a bit odd.

Let me know what you find. I suspect this to be more of a vimrc one liner or a change to vim-polyglot java syntax file.

**Comment by adelarsq** [comment]
I will keep you updated. I did some tests, but no solution until now.

**Comment by adelarsq** [comment]
After many attempts I haven't found any solution for this plugin to work together with [indentLine](https://github.com/Yggdroot/indentLine), since they share the same highlight for conceal.

I'm using [vim-indent-guides](https://github.com/nathanaelkane/vim-indent-guides) that works fine with this plugin.

I will close this issue for now.
